### ISSUE TITLE
RPT filled with "Performance warning: SimpleSerialization::Read"

### ISSUE THREAD

**Issue by JurijPietrowicz** [ArmaForces/SerialKillers#77]
Noticed numerous lines appearing in the RPT such as:

> 20:47:46 Performance warning: SimpleSerialization::Read 'afsk_civilian_location' is using type of ,'LOCATION' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

and

> 22:09:06 Performance warning: SimpleSerialization::Read 'CBAs' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

**Comment by veteran29** [comment]
`TEXT` and `LOCATION` types are being sent over network via CBA events.

**Comment by 3Mydlo3** [comment]
As for `LOCATION`, this is pretty straightforward. However, `TEXT` is a structured text, not a regular string, right? If so, I believe that's an issue with showing score changes via structured message that is created on the server. I'm working on changes in the area to get rid of that entirely.
